// Generated by scripts/write-mobile-build-channel.mjs.
export type MobileBuildChannel = 'internal' | 'production';

export const MOBILE_BUILD_CHANNEL = 'production' as MobileBuildChannel;

export const isInternalTestBuild = MOBILE_BUILD_CHANNEL === 'internal';
