// Generated by scripts/resolve-release-version.mjs.
export const RELEASE_INFO = {
  releaseTag: 'v0.0.0',
  versionName: '0.0.0',
  major: 0,
  minor: 0,
  patch: 0,
  buildNumber: 0,
  gitSha: 'local',
} as const;
