// Generated by scripts/write-ait-mp-config.mjs.
//
// GA4 Measurement Protocol API secret(비밀값)은 저장소에 커밋하지 않는다. 이 파일은
// 빈 placeholder로 커밋되고, 배포 빌드에서 GA4_MP_API_SECRET 환경변수 값으로 덮어써진다.
// (releaseInfo.ts와 동일한 "커밋된 placeholder를 빌드가 덮어쓰기" 패턴)
//
// 값이 비어 있으면 measurementProtocol 전송이 완전 no-op이 되어(로컬/개발 안전),
// 자체 지표 서버 seam(SELF_METRICS_ENDPOINT='')과 동일하게 동작한다.
export const GA4_MP_API_SECRET = '';
